language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - sudo apt-get update
  - sudo apt-get install libmpfr-dev
  - pip install Cython
  - pip install six
script:
  - python setup.py build_ext --inplace
  - python -m unittest discover -v
notifications:
  email:
    - dickinsm@gmail.com
